### ISSUE TITLE
Cannot connect to local gpd service.

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [darkfishy/uom-archlinux-globalprotect-bin#1]
Thanks for making available globalprotect in Arch.
It prevents me from using Arch.

After having created the package and install on my system, here is the error message I get:

```
❯ globalprotect
Cannot connect to local gpd service.
```
Any idea please?

**Comment by DavidPerezIngeniero** [comment]
Here is the definition of `gpd.service`:
```
[Unit]
Description=GlobalProtect VPN client daemon

[Service]
Type=simple
ExecStartPre=/opt/paloaltonetworks/globalprotect/pre_exec_gps.sh
ExecStart=/opt/paloaltonetworks/globalprotect/PanGPS
Restart=on-failure
RestartSec=5
WorkingDirectory=/opt/paloaltonetworks/globalprotect

[Install]
WantedBy=multi-user.target
```
I can place it in `/etc/systemd/system`.
Problem:
I don't have a *PanGPS* executable.

**Comment by DavidPerezIngeniero** [comment]
Finally I've been able to recreate the service.
```
❯ sudo systemctl status gpd
● gpd.service - GlobalProtect VPN client daemon
     Loaded: loaded (/etc/systemd/system/gpd.service; disabled; preset: disabled)
     Active: active (running) since Sat 2024-09-21 22:59:51 CEST; 8s ago
 Invocation: 88e8d1c812804097802d490779093667
    Process: 56028 ExecStartPre=/usr/local/bin/pre_exec_gps.sh (code=exited, status=0/SUCCESS)
   Main PID: 56042 (PanGPS)
      Tasks: 5 (limit: 19053)
     Memory: 18.3M (peak: 18.5M)
        CPU: 125ms
     CGroup: /system.slice/gpd.service
             └─56042 /usr/local/bin/PanGPS
```
but I get still:
```
❯ globalprotect 
Cannot connect to local gpd service.
```

**Comment by darkfishy** [comment]
G'day @DavidPerezIngeniero 

Just to clarify that this is not an official package from either GP or UoM, and is only relevant to connect to UoM VPN. 

> but I get still:
> 
> ```
> ❯ globalprotect 
> Cannot connect to local gpd service.
> ```

Firstly, check if any of the suggestions from the AUR page helps: https://aur.archlinux.org/packages/globalprotect-bin

Secondly, I think you have to start the GUI client by running `PanGPUI start`. Sometimes it doesn't work on the first go (as also noted by some on the AUR page), so you will have to kill the GUI process and start it again. 

Hope that helps.

Update: Also check the post install messages, because you need to start and/or enable user agent.

**Comment by DavidPerezIngeniero** [comment]
Now I've created:
```
  GNU nano 8.1                              /etc/systemd/system/gpa.service                                          
[Unit]
Description=GlobalProtect VPN client Agent

[Service]
Type=simple
ExecStart=/usr/local/bin/PanGPA start
Restart=on-failure
RestartSec=1
WorkingDirectory=/usr/local/bin

[Install]
WantedBy=default.target
```
and launch it with:
```
sudo systemctl daemon-reload
systemctl start --user gpa
```
and can now run:
```
❯ globalprotect launch-ui
UI Started Successfully
```
The only problem is that I don't see the UI.

**Comment by darkfishy** [comment]
> The only problem is that I don't see the UI.

It should appear in your DE/WM's system tray.

**Comment by DavidPerezIngeniero** [comment]
Thanks to your help it works with Arch Linux, I will document it in the AUR comments.
